# Generated by Django 3.1 on 2020-08-30 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('bookID', models.BigIntegerField()),
                ('bookShelfID', models.BigIntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('postDate', models.DateTimeField(verbose_name='date published')),
                ('postCover', models.ImageField(upload_to='images/')),
                ('like', models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL)),
                ('scrap', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
