# Generated by Django 3.1 on 2020-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_bookid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('bookCover', models.ImageField(upload_to='images/bookCover/')),
                ('description', models.CharField(max_length=5000)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='bookID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='postCover',
            field=models.ImageField(upload_to='images/postCover/'),
        ),
    ]
