# Generated by Django 3.1 on 2020-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200913_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postCover2',
            field=models.URLField(default='https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE2NTgyMX0', max_length=500),
            preserve_default=False,
        ),
    ]
