# Generated by Django 2.1.1 on 2020-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201008_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCover',
            field=models.ImageField(blank=True, null=True, upload_to='images/postCover/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCover2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
