# Generated by Django 3.1 on 2020-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201012_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='hahaha', max_length=5000),
            preserve_default=False,
        ),
    ]
