# Generated by Django 2.1.1 on 2020-10-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_book_description'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Post'),
        ),
    ]
