# Generated by Django 2.1.1 on 2020-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_book_description'),
        ('account', '0002_profile_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postID',
        ),
        migrations.AddField(
            model_name='profile',
            name='postID',
            field=models.ManyToManyField(related_name='myPost', to='home.Post'),
        ),
    ]
