# Generated by Django 3.1 on 2020-10-12 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20201009_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='myScrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
