# Generated by Django 3.1 on 2020-10-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201012_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scrap',
        ),
    ]
