# Generated by Django 3.1 on 2020-10-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201009_1805'),
        ('account', '0008_remove_profile_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='myScarp', to='home.Post'),
        ),
    ]
