# Generated by Django 3.1 on 2020-10-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0006_auto_20200830_2335'),
        ('account', '0009_profile_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookShelf',
            field=models.ManyToManyField(blank=True, related_name='myBookShelf', to='bookShelf.BookShelf'),
        ),
    ]
