# Generated by Django 3.1 on 2020-10-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_bookshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
