# Generated by Django 3.1 on 2020-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('postID', models.BigIntegerField(blank=True, null=True)),
                ('bookShelfTitle', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'bookShelfTitle',
                'verbose_name_plural': 'bookShelfTitles',
                'ordering': ('bookShelfTitle',),
            },
        ),
    ]
