# Generated by Django 3.1 on 2020-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='bookShelfTitle',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
