# Generated by Django 3.1 on 2020-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0002_auto_20200830_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='bookShelfTitle',
            field=models.CharField(max_length=250),
        ),
    ]
