# Generated by Django 3.1 on 2020-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0003_auto_20200830_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='bookShelfTitle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
