# Generated by Django 3.1 on 2020-10-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201012_1145'),
        ('bookShelf', '0006_auto_20200830_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='postID',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='postID',
            field=models.ManyToManyField(blank=True, related_name='post', to='home.Post'),
        ),
    ]
